// Copyright (C) 2025 Kampute
//
// Released under the terms of the MIT license.
// See the LICENSE file in the project root for the full license text.

namespace Kampute.DocToolkit.Models
{
    using Kampute.DocToolkit;
    using Kampute.DocToolkit.Metadata;
    using Kampute.DocToolkit.XmlDoc;
    using System;

    /// <summary>
    /// Represents a documentation model for a constructor within a type.
    /// </summary>
    /// <threadsafety static="true" instance="true"/>
    public class ConstructorModel : TypeMemberModel<IConstructor>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ConstructorModel"/> class.
        /// </summary>
        /// <param name="declaringType">The declaring type of the constructor.</param>
        /// <param name="constructor">The constructor information.</param>
        /// <exception cref="ArgumentNullException">Thrown when <paramref name="declaringType"/> or <paramref name="constructor"/> is <see langword="null"/>.</exception>
        /// <exception cref="ArgumentException">Thrown when <paramref name="constructor"/> is not a constructor of <paramref name="declaringType"/>.</exception>
        public ConstructorModel(TypeModel declaringType, IConstructor constructor)
            : base(declaringType, constructor)
        {
        }

        /// <summary>
        /// Gets the type of the documentation model.
        /// </summary>
        /// <value>
        /// The type of the documentation model, which is always <see cref="DocumentationModelType.Constructor"/> for this model.
        /// </value>
        public override DocumentationModelType ModelType => DocumentationModelType.Constructor;

        /// <summary>
        /// Gets a value indicating whether the constructor is a compiler-generated default constructor.
        /// </summary>
        /// <value>
        /// <see langword="true"/> if the constructor is a compiler-generated default constructor; otherwise, <see langword="false"/>.
        /// </value>
        /// <remarks>
        /// This property uses a heuristic approach to determine if the constructor is a compiler-generated default constructor. It assumes
        /// that a compiler-generated default constructor has no overloads, belongs to a class, and lacks any associated documentation comments.
        /// <note type="caution" title="Caution">
        /// This property may mistakenly identify undocumented user-defined default constructors as compiler-generated.
        /// <para>
        /// Since the compiler does not apply distinct attributes to generated default constructors, absolute determination is impossible.
        /// Therefore, treat this property as a hint rather than a definitive classification.
        /// </para>
        /// </note>
        /// </remarks>
        public bool IsAutoGenerated => Metadata.IsCompilerGenerated || (Metadata.Parameters.Count == 0 && Metadata.DeclaringType is ClassModel && Doc == XmlDocEntry.Empty && !Metadata.HasOverloads);

        /// <inheritdoc/>
        public override string ToString() => DeclaringType.Name;
    }
}
